# Practise During Class

# Numpy

In [2]:
import numpy as np
arr = np.array(12)
print(arr)
print(arr.ndim)

12
0


In [3]:
import numpy as np
arr = np.array([1,2,3,4,5], ndmin=5)
print(arr)
print(arr.ndim)

[[[[[1 2 3 4 5]]]]]
5


In [4]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[0])

1


In [6]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])

6


In [7]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(arr[1:5])

[2 3 4 5]


In [8]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[:4])

[1 2 3 4]


In [11]:
# Stepping with slicing
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[1::2])

[2 4 6 8]


In [12]:
# Stepping with slicing
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[1:8:2])

[2 4 6 8]


In [13]:
import numpy as np
arr = np.array([1,2,3,4,5,6], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5' b'6']
|S1


In [ ]:
import numpy as np
arr = np.array([1.1,2.1,3.1])
farr = arr.astype('i')

print(arr)
print(farr)

[1.1 2.1 3.1]
[1 2 3]


In [ ]:
# tells rows and columns (shape of the array)
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


In [21]:
# reshaping the array but if it exceeds the elements it will give error
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(arr)
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# iterating numpy arrays
import numpy as np
arr = np.array([1,2,3,4,5,6])
for x in arr:
    print(x, end=" ")

1 2 3 4 5 6 

In [31]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
for x in arr:
    for y in x:
        print(y, end=" ")

1 2 3 4 5 6 

In [35]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
    for y in x:
        for z in y:
            print(z, end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 

In [38]:
# nditer method is used to access each element of multidimentional array in a single loop
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in np.nditer(arr):
    print(x, end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 

In [42]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
newarr = np.array(np.array_split(arr,3))
print(newarr)
print(newarr.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [45]:
# split train and test data
from numpy import array
# define array
data = array([
[11, 22, 33],
[44, 55, 66],
[77, 88, 99]])
# separate data
split = 2
train,test = data[:split,:],data[split:,:]
print("Train:",train)
print("Test:",test)

Train: [[11 22 33]
 [44 55 66]]
Test: [[77 88 99]]


# Pandas

In [46]:
import pandas as pd
print(pd.__version__)

3.0.0


In [55]:
import pandas as pd
mydataset = {
    "Cars": ["BMW", "Suzuki", "Ford","Toyota", "Nissan", "Lamborghini"],
    "Passings": [4,2,6,3,8,9]
}
df = pd.DataFrame(mydataset)
print(df)

          Cars  Passings
0          BMW         4
1       Suzuki         2
2         Ford         6
3       Toyota         3
4       Nissan         8
5  Lamborghini         9


In [53]:
# .head() function is used to access/view the first five records/rows of the dataset
import pandas as pd
mydataset = {
    "Cars": ["BMW", "Suzuki", "Ford","Toyota", "Nissan", "Lamborghini"],
    "Passings": [4,2,6,3,8,9]
}
df = pd.DataFrame(mydataset)
df.head()

Cars  Passings
0     BMW         4
1  Suzuki         2
2    Ford         6
3  Toyota         3
4  Nissan         8

In [56]:
import pandas as pd
a = [41,43,12]
b = pd.Series(a)
print(b)

0    41
1    43
2    12
dtype: int64


In [58]:
import pandas as pd
a = [41,43,12]
b = pd.Series(a, index = ["a","b", "c"])
print(b)
print(b["a"])

a    41
b    43
c    12
dtype: int64
41


In [60]:
import pandas as pd
calories = {"Day1": 12, "Day2": 13, "Day3": 14}
abc = pd.Series(calories)
print(abc)

Day1    12
Day2    13
Day3    14
dtype: int64


In [61]:
import pandas as pd
calories = {"Day1": 12, "Day2": 13, "Day3": 14}
abc = pd.Series(calories, index = ["Day1", "Day2"])
print(abc)

Day1    12
Day2    13
dtype: int64


In [62]:
import pandas as pd
data = {
    "calories": [210,432,780],
    "duration": [20,30,40]
}
a = pd.DataFrame(data)
print(a)

   calories  duration
0       210        20
1       432        30
2       780        40


In [69]:
# .loc[] function is used to access any row
import pandas as pd
data = {
    "calories": [210,432,780],
    "duration": [20,30,40]
}
df = pd.DataFrame(data)
print(df.loc[0])

calories    210
duration     20
Name: 0, dtype: int64


In [68]:
# List of indexes to locate multiple rows
import pandas as pd
data = {
    "calories": [210,432,780],
    "duration": [20,30,40]
}
df = pd.DataFrame(data)
print(df.loc[[0, 1]])

   calories  duration
0       210        20
1       432        30


In [72]:
# giving each row a name and accessing that row by that specific index/name in .loc[] function
import pandas as pd
data = {
    "calories": [210,432,780],
    "duration": [20,30,40]
}
df = pd.DataFrame(data, index = ["Day1", "Day2", "Day3"])
print(df)
print("first row only:",df.loc["Day1"])

      calories  duration
Day1       210        20
Day2       432        30
Day3       780        40
first row only: calories    210
duration     20
Name: Day1, dtype: int64


In [84]:
# Loading a dataset into DataFrame
import pandas as pd
path = r"C:\Users\User\Downloads\Students Social Media Addiction.csv"
df = pd.read_csv(path)
df.head()

Student_ID  Age  Gender Academic_Level     Country  Avg_Daily_Usage_Hours  \
0           1   19  Female  Undergraduate  Bangladesh                    5.2   
1           2   22    Male       Graduate       India                    2.1   
2           3   20  Female  Undergraduate         USA                    6.0   
3           4   18    Male    High School          UK                    3.0   
4           5   21    Male       Graduate      Canada                    4.5   

  Most_Used_Platform Affects_Academic_Performance  Sleep_Hours_Per_Night  \
0          Instagram                          Yes                    6.5   
1            Twitter                           No                    7.5   
2             TikTok                          Yes                    5.0   
3            YouTube                           No                    7.0   
4           Facebook                          Yes                    6.0   

   Mental_Health_Score Relationship_Status  Conflicts_Over_Social_Media  \
0                    6     In Relationship                            3   
1                    8              Single                            0   
2                    5         Complicated                            4   
3                    7              Single                            1   
4                    6     In Relationship                            2   

   Addicted_Score  
0               8  
1               3  
2               9  
3               4  
4               7