# Basics of Python

In [1]:
print("Hello world")

Hello world


In [ ]:
import pandas as pd
s1_employees = {
    "ID": [101, 102, 103, 104, 105],
    "Name": ["Sara", "Ahmed", "John", "Maria", "Ali"],
    "Role": ["AI Engineer", "Data Analyst", "ML Ops", "AI Engineer", "Data Analyst"],
    "Salary": [95000, 72000, 88000, 105000, 65000],
    "Experience": [3,1,5,4,2]
}
df = pd.DataFrame(s1_employees)
# show only AI Engineers who have more than 3 years of experience
print("AI Engineers with more than 3 years of experience:\n",df[(df["Role"] == "AI Engineer") & (df["Experience"] > 3)])
# calculate the average salary grouped by Role
print("Average salary grouped by Role:\n",df.groupby("Role")["Salary"].mean())

# add a column level: "Senior" if experience >= 4 else "Junior"
exp = []
for x in df["Experience"]:
    if x >= 4:
        exp.append("Senior")
    else:
        exp.append("Junior")
df["Level"] = exp
df.head()

AI Engineers with more than 3 years of experience:
     ID   Name         Role  Salary  Experience
3  104  Maria  AI Engineer  105000           4
Average salary grouped by Role:
 Role
AI Engineer     100000.0
Data Analyst     68500.0
ML Ops           88000.0
Name: Salary, dtype: float64


,ID,Name,Role,Salary,Experience,Level
0,101,Sara,AI Engineer,95000,3,Junior
1,102,Ahmed,Data Analyst,72000,1,Junior
2,103,John,ML Ops,88000,5,Senior
3,104,Maria,AI Engineer,105000,4,Senior
4,105,Ali,Data Analyst,65000,2,Junior


In [33]:
import numpy as np
# create a 5*5 array containing random integers 10 and 100
arr = np.random.randint(10, 100, (5, 5))
mean_arr = np.mean(arr)
print("All the values greater than the mean are:")
print(arr[arr > mean_arr])
    
arr[arr < 50] = 0

print("\nMean of the array is:", mean_arr)
print("Modified array: ")
print(arr)

All the values greater than the mean are:
[67 76 98 93 81 80 80 74 61 89 61 82 63 62]

Mean of the array is: 58.0
Modified array: 
[[67  0  0 76 98]
 [93  0  0 81  0]
 [80 80 74 61 55]
 [ 0  0  0 89  0]
 [61 82  0 63 62]]


In [36]:
import pandas as pd
s1_employees = {
    "ID": [101, 102, 103, 104, 105],
    "Name": ["Sara", "Ahmed", "John", "Maria", "Ali"],
    "Role": ["AI Engineer", "Data Analyst", "ML Ops", "AI Engineer", "Data Analyst"],
    "Salary": [95000, 72000, 88000, 105000, 65000],
    "Experience": [3,1,5,4,2]
}
df = pd.DataFrame(s1_employees)
df.loc[2, "Salary"] = None
df["Salary"] = df["Salary"].fillna(df["Salary"].median())
df["Salary"].sort_values(ascending=False)

3    105000.0
0     95000.0
2     83500.0
1     72000.0
4     65000.0
Name: Salary, dtype: float64